### PR TITLE
Updated obfstr

### PR DESCRIPTION
**Pull request by PotatoSUS**

### CODE REVIEW

**Comment by x4e** [comment]
Hello, could you please confirm that you have ensured that this change works? As in, you have successfully used the project with this change implemented.
Thanks for submitting your contribution.

**Comment by PotatoSUS** [comment]
yes the update works, with the old version of obfstr it gave an error of RUSTC_BOOTLOADER=-1, updating was fixed, the only error that remains in the build is the one I sent you in the email, but only on windows, when I tried to build on linux built normally

**Comment by jabask3dd3r** [comment]
Hello, how i can use this??? can make sample project with this?????

**Comment by PotatoSUS** [comment]
coding a jni loader, take a look on raion loader https://github.com/Ropro2002/raion-public

**Comment by x4e** [comment]
Thanks :)

**Pull request merged**
